image: continuumio/anaconda3

pages:
  stage: deploy
  before_script:
    - echo "Install additional packages"
    - pip install -I sphinx==2.3.1
    - pip install sphinx-rtd-theme
    - pip install sphinxcontrib-wavedrom
    - pip install sphinxcontrib-plantuml
    - pip install recommonmark
    - pip install sphinxemoji
    - apt-get update
    - echo "Install build-essential"
    - apt-get install -y build-essential
    - echo "Install git"
    - apt-get install -y git
    - echo "Install graphviz"
    - apt-get install -y graphviz
    - echo "Install Inkscape"
    - apt-get install -y inkscape
    - echo "Install texlive"
    - apt-get install -y texlive-full
    - chmod +x /builds/SPL/spl-docs/source/_static/plantuml.jar
    - echo "Install Java"
    - dpkg --configure -a
    - mkdir -p /usr/share/man/man1
    - apt-get install -y openjdk-11-jre
  script:
    #- make latexpdf
    #- make clean
    - make html
  artifacts:
    paths:
      - public
  only:
    - master
