language: python

python:
  - 3.7

dist: xenial
sudo: true

stages:
  - test-links
  - build
  - name: deploy-html
    if: branch = master  # Deploy only on master commits
  #- name: deploy-pdf
  #  if: branch = master  # Deploy only on master commits

install:
  - echo "Install additional packages"
  - pip install sphinx-rtd-theme
  - pip install sphinxcontrib-wavedrom
  - pip install sphinxcontrib-plantuml
  - pip install recommonmark
  - apt-get update
  - echo "Install build-essential"
  - apt-get install -y build-essential
  - echo "Install git"
  - apt-get install -y git
  - echo "Install graphviz"
  - apt-get install -y graphviz
  - echo "Install Inkscape"
  - apt-get install -y inkscape
  - echo "Install texlive"
  - apt-get install -y texlive-full
  - chmod +x source/_static/plantuml.jar
  - echo "Install Java"
  - dpkg --configure -a
  - mkdir -p /usr/share/man/man1
  - apt-get install -y openjdk-11-jre

jobs:
  include:
    - stage: test-links
      script: make linkcheck
    - stage: build
      script: make html
      script: make latexpdf
    - stage: deploy-html
      script: make html
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local-dir: public
        on:
          branch: master  # You can't be safe enough <insert double condom joke here>
    - stage: deploy-pdf
      script: make latexpdf
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        # local-dir: public/pdf
        file:
          - pdf/Cheatsheets.pdf
        on:
          branch: master  # You can't be safe enough <insert double condom joke here>

