language: python

python:
  - 3.7

dist: xenial
sudo: true

stages:
  - name: deploy-html
    if: branch = master  # Deploy only on master commits

install:
  - echo "Install additional packages"
  - pip install -I sphinx==2.3.1
  - pip install sphinx-rtd-theme
  - pip install sphinxcontrib-wavedrom
  - pip install sphinxcontrib-plantuml
  - pip install recommonmark
  - pip install sphinxemoji
  - pip install sphinx-copybutton
  - sudo apt-get update
  - echo "Install build-essential"
  - sudo apt-get install -y build-essential
  - echo "Install git"
  - sudo apt-get install -y git
  - echo "Install graphviz"
  - sudo apt-get install -y graphviz
  - echo "Install Inkscape"
  - sudo apt-get install -y inkscape
  - echo "Install texlive"
  #- sudo apt-get install -y texlive-full
  - chmod +x source/_static/jar/plantuml.jar
  - echo "Install Java"
  - sudo dpkg --configure -a
  - mkdir -p /usr/share/man/man1
  - sudo apt-get install -y default-jdk

jobs:
  include:
    - stage: deploy-html
      script: make html
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the travis settings page for this repo, as a secure variable
        keep-history: true
        local-dir: _build/html
        on:
          branch: master