# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
import subprocess
from datetime import datetime
sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------
AUTHOR='tschinz'
VERSION = subprocess.check_output(["git", "describe"]).decode('UTF-8')

project = 'Zawiki'
copyright = f"2004-{datetime.now().year}, tschinz"
author = AUTHOR

# The short X.Y version
version = VERSION
# The full version, including alpha/beta/rc tags
release = VERSION


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    #"sphinx.ext.autodoc",
    #"sphinx.ext.autosummary",
    #"sphinx.ext.doctest",
    #"sphinx.ext.intersphinx",
    #"sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.ifconfig",
    "sphinx.ext.graphviz",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.todo",
    "sphinx.ext.extlinks",
    "sphinx.ext.githubpages",
    "sphinxcontrib.wavedrom",
    "sphinxcontrib.plantuml",
    #"jupyter_sphinx",
    "recommonmark",
    "sphinx_copybutton",
    "sphinxemoji.sphinxemoji",
    #"nbsphinx",
    #"matplotlib.sphinxext.plot_directive",
    #"IPython.sphinxext.ipython_console_highlighting",
    #"IPython.sphinxext.ipython_directive",
]

# emoij style
#sphinxemoji_style = 'twemoji'

# external Links
extlinks = {'config_repo': ('https://github.com/tschinz/config/%s', None),
            'zawiki_repo': ('https://github.com/tschinz/zawiki/%s', None),
            'zawiki_page': ('http://tschinz.github.io/zawiki/%s', None),
            'pdfviewer': ('https://nbviewer.jupyter.org/%s', None),
            }

# Avoid warnings when different pages have the same titles
autosectionlabel_prefix_document = True

# Plant uml Jar file
plantuml = "java -jar -Djava.awt.headless=true " + os.path.abspath("." + os.sep + "_static" + os.sep + "jar" + os.sep + "plantuml.jar")

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ['.rst', '.md']
# source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'pastie'
#pygments_style = 'monokai'
pygments_style = "sphinx"
#pygments_style = 'manni'
#pygments_style = 'default'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'sphinx_rtd_theme'
html_theme = "pydata_sphinx_theme"
# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
html_favicon = 'img/favicon.png'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Copybutton image path
copybutton_image_path = 'img/copybutton.svg'

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# -- Options for LaTeX output ------------------------------------------------
latex_engine = 'xelatex'
latex_elements = {
    'fncychap': r'\usepackage[Bjornstrup]{fncychap}',
    'printindex': r'\footnotesize\raggedright\printindex',

    'papersize': 'a4paper',

    'pointsize': '10pt',
    'extraclassoptions': 'onecolumn,oneside',
    'passoptionstopackages': '\\PassOptionsToPackage{warn}{textcomp}',

    'inputenc': '',
    'fncychap': '',
    'utf8extra': '',
    'fontpkg': '',
    'babel': '\\usepackage{polyglossia}',
    'cmappkg': '',
    'fontenc': '',
    'releasename': '',

    'fontpkg': r'''
        \setmainfont{DejaVu Serif}
        \setsansfont{DejaVu Sans}
        \setmonofont{DejaVu Sans Mono}
    ''',

    'preamble': r'''
        % !Tex program = xelatex
        \usepackage[titles]{tocloft}
        \cftsetpnumwidth {1.25cm}\cftsetrmarg{1.5cm}
        \setlength{\cftchapnumwidth}{0.75cm}
        \setlength{\cftsecindent}{\cftchapnumwidth}
        \setlength{\cftsecnumwidth}{1.25cm}
    ''',

    # Latex figure (float) alignment
    #
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'zawiki.tex', 'Zawiki',
      AUTHOR, 'manual'),
]

latex_logo = 'img/logo.pdf'

# -- Extension configuration -------------------------------------------------
# -- Options for pydata-sphinx-theme -----------------------------------------
html_theme_options = {
  "external_links": [
      {"name": "Config repo", "url": "https://github.com/tschinz/config"},
  ],
  "google_analytics_id": "UA-20699788-1",
  "github_url": "https://github.com/tschinz/zawiki",
  "twitter_url": "https://twitter.com/tschinz",
  "show_prev_next": False,
  "search_bar_position": "navbar", #"sidebar"
  "search_bar_text": "Don't panic, search",
  "use_edit_page_button": True,
}
html_context = {
    'css_files': [
        '_static/css/theme_overrides.css',  # override wide tables in RTD theme
        '_static/css/copy_button.css',      # override copybutton on code-block
    ],
    "github_user": "tschinz",
    "github_repo": "zawiki",
    "github_version": "master",
    "doc_path": "source",
}

html_logo = 'img/logo.svg'
html_title = 'Zawiki'
# This is a temporary fix for wavedrom
offline_skin_js_path = "_static/js/default.js"
offline_wavedrom_js_path = "_static/js/wavedrom.min.js"

# Option for linkcheck
linkcheck_anchors=False

# -- RST Epilog ----------------------------------------------------------
rst_epilog = """
.. |folder| image:: /img/icons/folder.*
.. |file| image:: /img/icons/file.*
.. |sign-check| image:: /img/icons/success.*

.. |star5| image:: /img/icons/star-5.*
.. |star4| image:: /img/icons/star-4.*
.. |star3| image:: /img/icons/star-3.*
.. |star2| image:: /img/icons/star-2.*
.. |star1| image:: /img/icons/star-1.*
.. |star| image:: /img/icons/star.*

.. |en| image:: /img/icons/uk.*
.. |ch| image:: /img/icons/switzerland.*
.. |de| image:: /img/icons/germany.*
.. |china| image:: /img/icons/china.*
.. |uk| image:: /img/icons/uk.*
.. |usa| image:: /img/icons/usa.*
.. |it| image:: /img/icons/italy.*
.. |jp| image:: /img/icons/japan.*
.. |fr| image:: /img/icons/france.*

.. |linux| image:: /img/icons/linux.*
.. |mac| image:: /img/icons/apple.*
.. |win| image:: /img/icons/windows.*

.. |word| image:: /img/icons/word.*
.. |excel| image:: /img/icons/excel.*
.. |onenote| image:: /img/icons/onenote.*
.. |outlook| image:: /img/icons/outlook.*
"""