name: Build Sphinx to Github Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file condaenv.yml --name base
        #sudo apt-get install -y graphviz
        #sudo apt-get install -y inkscape
        #sudo apt-get install -y texlive-full
        #sudo dpkg --configure -a
        #mkdir -p /usr/share/man/man1
        #sudo apt-get install -y default-jdk
    - name: Lint with flake8
      run: |
        $CONDA/bin/conda make html
