name: Build Sphinx to Github Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -U sphinx
        pip install -U pydata-sphinx-theme
        pip install -U sphinxcontrib-wavedrom
        pip install -U sphinxcontrib-plantuml
        #- pip install -U recommonmark
        pip install -U sphinxemoji
        pip install -U sphinx-copybutton
        #- pip install -U nbsphinx
        #- pip install -U jupyter_sphinx
        pip install -U sphinx-panels
        pip install -U sphinx-autobuild
        pip install -U sphinx-notfound-page
        sudo apt-get update
        echo "Install build-essential"
        sudo apt-get install -y build-essential
        echo "Install git"
        sudo apt-get install -y git
        echo "Install graphviz"
        sudo apt-get install -y graphviz
        echo "Install Inkscape"
        sudo apt-get install -y inkscape
        echo "Install texlive"
        #- sudo apt-get install -y texlive-full
        chmod +x source/_static/jar/plantuml.jar
        echo "Install Java"
        sudo dpkg --configure -a
        mkdir -p /usr/share/man/man1
        sudo apt-get install -y default-jdk
    - name: build sphinx
      run: |
        make html
    - name: publish
      run: |
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
